version: "3.9"
services:
  postgres:
    image: postgres:10.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: training
    ports:
      - 35000:5432

    ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

  migration: 
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run migrate
    depends_on: 
      - postgres

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run start:debug
    depends_on: 
      - postgres
    environment: 
      NODE_ENV: development
      APP_PORT: 3000
      JWT_SECRET_KEY: thisIsJWTKey
      JWT_EXPIRE_TIME: 60m
      JWT_REFRESH_SECRET_KEY: thisIsJWTRefreshKey
      JWT_REFRESH_EXPIRE_TIME: 75m
      DATABASE_TYPE: postgres
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 35000
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: training
      SWAGGER_PATH: swagger
      SWAGGER_DISABLE: "false"
      SWAGGER_TITLE: Training API
      SWAGGER_DESCRIPTION: Training API document
      SWAGGER_VERSION: 1.0
    ports:
      - 3000:3000
      - 9229:9229

  